[2025-06-25T11:49:39.787+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:46:14+00:00 [queued]>
[2025-06-25T11:49:39.815+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:46:14+00:00 [queued]>
[2025-06-25T11:49:39.816+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T11:49:40.029+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 09:46:14+00:00
[2025-06-25T11:49:40.037+0200] {standard_task_runner.py:57} INFO - Started process 232375 to run task
[2025-06-25T11:49:40.094+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T09:46:14+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpkq6crv4f']
[2025-06-25T11:49:40.102+0200] {standard_task_runner.py:85} INFO - Job 47: Subtask run_dbt_models
[2025-06-25T11:49:40.355+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:46:14+00:00 [running]> on host 192.168.152.131
[2025-06-25T11:49:40.460+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T09:46:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T09:46:14+00:00'
[2025-06-25T11:49:40.465+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T11:49:40.467+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T11:49:40.704+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T11:49:43.699+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T11:49:43.701+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T11:49:45.241+0200] {subprocess.py:93} INFO - [0m09:49:45  Running with dbt=1.10.2
[2025-06-25T11:49:46.965+0200] {subprocess.py:93} INFO - [0m09:49:46  Registered adapter: snowflake=1.9.4
[2025-06-25T11:49:48.537+0200] {subprocess.py:93} INFO - [0m09:49:48  Found 4 models, 476 macros
[2025-06-25T11:49:48.542+0200] {subprocess.py:93} INFO - [0m09:49:48
[2025-06-25T11:49:48.544+0200] {subprocess.py:93} INFO - [0m09:49:48  Concurrency: 1 threads (target='dev')
[2025-06-25T11:49:48.546+0200] {subprocess.py:93} INFO - [0m09:49:48
[2025-06-25T11:49:51.209+0200] {subprocess.py:93} INFO - [0m09:49:51  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T11:49:51.895+0200] {subprocess.py:93} INFO - [0m09:49:51  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.68s]
[2025-06-25T11:49:51.902+0200] {subprocess.py:93} INFO - [0m09:49:51  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T11:49:52.261+0200] {subprocess.py:93} INFO - [0m09:49:52  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.35s]
[2025-06-25T11:49:52.270+0200] {subprocess.py:93} INFO - [0m09:49:52  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T11:49:52.644+0200] {subprocess.py:93} INFO - [0m09:49:52  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.37s]
[2025-06-25T11:49:52.653+0200] {subprocess.py:93} INFO - [0m09:49:52  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T11:49:53.141+0200] {subprocess.py:93} INFO - [0m09:49:53  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.49s]
[2025-06-25T11:49:53.836+0200] {subprocess.py:93} INFO - [0m09:49:53
[2025-06-25T11:49:53.838+0200] {subprocess.py:93} INFO - [0m09:49:53  Finished running 4 view models in 0 hours 0 minutes and 5.29 seconds (5.29s).
[2025-06-25T11:49:53.915+0200] {subprocess.py:93} INFO - [0m09:49:53
[2025-06-25T11:49:53.917+0200] {subprocess.py:93} INFO - [0m09:49:53  [32mCompleted successfully[0m
[2025-06-25T11:49:53.918+0200] {subprocess.py:93} INFO - [0m09:49:53
[2025-06-25T11:49:53.920+0200] {subprocess.py:93} INFO - [0m09:49:53  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T11:49:54.377+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T11:49:54.472+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T094614, start_date=20250625T094939, end_date=20250625T094954
[2025-06-25T11:49:54.554+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T11:49:54.622+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
