[2025-06-24T23:15:10.482+0200] {processor.py:157} INFO - Started process (PID=154804) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:15:10.504+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T23:15:10.509+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:15:10.508+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:15:10.541+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:15:10.533+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T23:15:10.554+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:15:10.554+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T23:15:10.557+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:15:10.688+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.277 seconds
[2025-06-24T23:16:40.932+0200] {processor.py:157} INFO - Started process (PID=155210) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:16:40.940+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T23:16:40.942+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:16:40.942+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:16:40.955+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:16:40.953+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T23:16:40.956+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:16:40.956+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T23:16:40.957+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:16:41.007+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2025-06-24T23:17:44.394+0200] {processor.py:157} INFO - Started process (PID=155345) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:17:44.400+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T23:17:44.404+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:17:44.403+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:17:44.434+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:17:44.429+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T23:17:44.436+0200] {logging_mixin.py:149} INFO - [2025-06-24T23:17:44.436+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T23:17:44.438+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T23:17:44.510+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.138 seconds
[2025-06-25T01:11:51.178+0200] {processor.py:157} INFO - Started process (PID=173285) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:11:51.231+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:11:51.243+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:11:51.241+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:11:51.297+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:11:51.286+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:11:51.300+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:11:51.300+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:11:51.302+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:11:51.475+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.361 seconds
[2025-06-25T01:18:13.785+0200] {processor.py:157} INFO - Started process (PID=175072) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:18:13.824+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:18:13.861+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:18:13.861+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:18:13.981+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:18:13.948+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:18:13.981+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:18:13.981+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:18:13.982+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:18:14.291+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.612 seconds
[2025-06-25T01:19:42.747+0200] {processor.py:157} INFO - Started process (PID=175709) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:19:42.752+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:19:42.753+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:19:42.753+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:19:42.763+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:19:42.761+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:19:42.764+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:19:42.764+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:19:42.765+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:19:42.799+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-06-25T01:21:32.985+0200] {processor.py:157} INFO - Started process (PID=176843) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:21:32.993+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:21:32.997+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:21:32.997+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:21:33.013+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:21:33.011+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:21:33.015+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:21:33.015+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:21:33.016+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:21:33.090+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2025-06-25T01:22:46.583+0200] {processor.py:157} INFO - Started process (PID=177077) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:22:46.588+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:22:46.590+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:22:46.590+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:22:46.602+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:22:46.599+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:22:46.603+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:22:46.603+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:22:46.603+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:22:46.640+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-06-25T01:24:30.554+0200] {processor.py:157} INFO - Started process (PID=177896) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:24:30.571+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:24:30.574+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:24:30.574+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:24:30.621+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:24:30.618+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:24:30.649+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:24:30.649+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:24:30.651+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:24:30.804+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.305 seconds
[2025-06-25T01:26:41.558+0200] {processor.py:157} INFO - Started process (PID=178905) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:26:41.565+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:26:41.568+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:26:41.567+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:26:41.603+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:26:41.590+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:26:41.604+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:26:41.604+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:26:41.605+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:26:41.765+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.228 seconds
[2025-06-25T01:29:30.084+0200] {processor.py:157} INFO - Started process (PID=180120) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:29:30.095+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:29:30.099+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:29:30.099+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:29:30.137+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:29:30.130+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:29:30.140+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:29:30.139+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:29:30.152+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:29:30.314+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.279 seconds
[2025-06-25T01:31:22.300+0200] {processor.py:157} INFO - Started process (PID=181159) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:31:22.333+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:31:22.353+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:31:22.353+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:31:22.380+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:31:22.374+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:31:22.386+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:31:22.386+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:31:22.388+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:31:22.468+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.222 seconds
[2025-06-25T01:32:33.354+0200] {processor.py:157} INFO - Started process (PID=181415) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:32:33.359+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:32:33.362+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:32:33.362+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:32:33.373+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:32:33.371+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:32:33.374+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:32:33.374+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:32:33.375+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:32:33.413+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-06-25T01:34:41.230+0200] {processor.py:157} INFO - Started process (PID=182086) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:34:41.249+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:34:41.254+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:34:41.254+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:34:41.278+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:34:41.274+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:34:41.283+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:34:41.283+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:34:41.285+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:34:41.384+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.188 seconds
[2025-06-25T01:38:22.697+0200] {processor.py:157} INFO - Started process (PID=183497) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:38:22.702+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:38:22.705+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:38:22.705+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:38:22.716+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:38:22.714+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:38:22.717+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:38:22.717+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:38:22.717+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:38:22.755+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-06-25T01:39:32.666+0200] {processor.py:157} INFO - Started process (PID=183726) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:39:32.672+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:39:32.677+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:39:32.676+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:39:32.695+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:39:32.689+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:39:32.696+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:39:32.696+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:39:32.698+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:39:32.811+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2025-06-25T01:41:05.928+0200] {processor.py:157} INFO - Started process (PID=183988) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:41:05.933+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:41:05.936+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:41:05.935+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:41:05.950+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:41:05.948+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:41:05.951+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:41:05.951+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:41:05.953+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:41:06.001+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2025-06-25T01:45:54.052+0200] {processor.py:157} INFO - Started process (PID=187412) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:45:54.058+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:45:54.061+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:45:54.060+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:45:54.160+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:45:54.157+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:45:54.161+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:45:54.161+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:45:54.162+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:45:54.210+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.177 seconds
[2025-06-25T01:47:20.479+0200] {processor.py:157} INFO - Started process (PID=188266) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:47:20.486+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:47:20.490+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:47:20.489+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:47:20.505+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:47:20.501+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:47:20.507+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:47:20.506+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:47:20.509+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:47:20.680+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.219 seconds
[2025-06-25T01:49:33.267+0200] {processor.py:157} INFO - Started process (PID=189197) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:49:33.277+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:49:33.283+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:49:33.283+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:49:33.322+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:49:33.313+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:49:33.325+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:49:33.325+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:49:33.326+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:49:33.431+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.203 seconds
[2025-06-25T01:50:57.786+0200] {processor.py:157} INFO - Started process (PID=189614) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:50:57.817+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:50:57.826+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:50:57.825+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:50:57.885+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:50:57.878+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:50:57.886+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:50:57.886+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:50:57.890+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:50:58.168+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.450 seconds
[2025-06-25T01:52:46.535+0200] {processor.py:157} INFO - Started process (PID=190042) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:52:46.540+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:52:46.542+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:52:46.542+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:52:46.555+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:52:46.553+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:52:46.556+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:52:46.556+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:52:46.557+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:52:46.596+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-06-25T01:55:49.356+0200] {processor.py:157} INFO - Started process (PID=190949) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:55:49.361+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:55:49.363+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:55:49.362+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:55:49.374+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:55:49.371+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:55:49.375+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:55:49.375+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:55:49.376+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:55:49.412+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-06-25T01:57:06.357+0200] {processor.py:157} INFO - Started process (PID=191370) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:57:06.452+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:57:06.463+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:57:06.462+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:57:06.541+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:57:06.529+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:57:06.542+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:57:06.542+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:57:06.547+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:57:06.758+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.891 seconds
[2025-06-25T01:59:51.481+0200] {processor.py:157} INFO - Started process (PID=192974) to work on /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:59:51.485+0200] {processor.py:826} INFO - Processing file /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-25T01:59:51.488+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:59:51.487+0200] {dagbag.py:541} INFO - Filling up the DagBag from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:59:51.498+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:59:51.496+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-25T01:59:51.499+0200] {logging_mixin.py:149} INFO - [2025-06-25T01:59:51.499+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-25T01:59:51.500+0200] {processor.py:838} WARNING - No viable dags retrieved from /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-25T01:59:51.536+0200] {processor.py:179} INFO - Processing /home/atef/.local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
