[2025-06-25T08:56:13.957+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T06:56:05.309066+00:00 [queued]>
[2025-06-25T08:56:13.965+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T06:56:05.309066+00:00 [queued]>
[2025-06-25T08:56:13.966+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T08:56:14.013+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 06:56:05.309066+00:00
[2025-06-25T08:56:14.018+0200] {standard_task_runner.py:57} INFO - Started process 216561 to run task
[2025-06-25T08:56:14.050+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T06:56:05.309066+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp0b1bqig2']
[2025-06-25T08:56:14.057+0200] {standard_task_runner.py:85} INFO - Job 27: Subtask run_dbt_models
[2025-06-25T08:56:14.171+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T06:56:05.309066+00:00 [running]> on host 192.168.152.131
[2025-06-25T08:56:14.287+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T06:56:05.309066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T06:56:05.309066+00:00'
[2025-06-25T08:56:14.292+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T08:56:14.294+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T08:56:14.315+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T08:56:17.727+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T08:56:17.728+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T08:56:18.673+0200] {subprocess.py:93} INFO - [0m06:56:18  Running with dbt=1.10.2
[2025-06-25T08:56:21.949+0200] {subprocess.py:93} INFO - [0m06:56:21  Registered adapter: snowflake=1.9.4
[2025-06-25T08:56:27.037+0200] {subprocess.py:93} INFO - [0m06:56:27  Found 4 models, 476 macros
[2025-06-25T08:56:27.046+0200] {subprocess.py:93} INFO - [0m06:56:27
[2025-06-25T08:56:27.048+0200] {subprocess.py:93} INFO - [0m06:56:27  Concurrency: 1 threads (target='dev')
[2025-06-25T08:56:27.051+0200] {subprocess.py:93} INFO - [0m06:56:27
[2025-06-25T08:56:29.600+0200] {subprocess.py:93} INFO - [0m06:56:29  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T08:56:30.346+0200] {subprocess.py:93} INFO - [0m06:56:30  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.74s]
[2025-06-25T08:56:30.360+0200] {subprocess.py:93} INFO - [0m06:56:30  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T08:56:30.747+0200] {subprocess.py:93} INFO - [0m06:56:30  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.38s]
[2025-06-25T08:56:30.754+0200] {subprocess.py:93} INFO - [0m06:56:30  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T08:56:31.118+0200] {subprocess.py:93} INFO - [0m06:56:31  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T08:56:31.125+0200] {subprocess.py:93} INFO - [0m06:56:31  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T08:56:31.645+0200] {subprocess.py:93} INFO - [0m06:56:31  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.51s]
[2025-06-25T08:56:32.352+0200] {subprocess.py:93} INFO - [0m06:56:32
[2025-06-25T08:56:32.356+0200] {subprocess.py:93} INFO - [0m06:56:32  Finished running 4 view models in 0 hours 0 minutes and 5.30 seconds (5.30s).
[2025-06-25T08:56:32.481+0200] {subprocess.py:93} INFO - [0m06:56:32
[2025-06-25T08:56:32.484+0200] {subprocess.py:93} INFO - [0m06:56:32  [32mCompleted successfully[0m
[2025-06-25T08:56:32.486+0200] {subprocess.py:93} INFO - [0m06:56:32
[2025-06-25T08:56:32.490+0200] {subprocess.py:93} INFO - [0m06:56:32  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T08:56:32.947+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T08:56:33.026+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T065605, start_date=20250625T065613, end_date=20250625T065633
[2025-06-25T08:56:33.128+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T08:56:33.213+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
