[2025-06-25T09:27:57.114+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:27:48.440818+00:00 [queued]>
[2025-06-25T09:27:57.134+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:27:48.440818+00:00 [queued]>
[2025-06-25T09:27:57.136+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T09:27:57.177+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 07:27:48.440818+00:00
[2025-06-25T09:27:57.190+0200] {standard_task_runner.py:57} INFO - Started process 226941 to run task
[2025-06-25T09:27:57.356+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T07:27:48.440818+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpxs747nw2']
[2025-06-25T09:27:57.373+0200] {standard_task_runner.py:85} INFO - Job 37: Subtask run_dbt_models
[2025-06-25T09:27:57.625+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:27:48.440818+00:00 [running]> on host 192.168.152.131
[2025-06-25T09:27:57.799+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T07:27:48.440818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T07:27:48.440818+00:00'
[2025-06-25T09:27:57.804+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T09:27:57.805+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T09:27:57.958+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T09:28:01.134+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T09:28:01.136+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T09:28:02.296+0200] {subprocess.py:93} INFO - [0m07:28:02  Running with dbt=1.10.2
[2025-06-25T09:28:04.154+0200] {subprocess.py:93} INFO - [0m07:28:04  Registered adapter: snowflake=1.9.4
[2025-06-25T09:28:06.094+0200] {subprocess.py:93} INFO - [0m07:28:06  Found 4 models, 476 macros
[2025-06-25T09:28:06.101+0200] {subprocess.py:93} INFO - [0m07:28:06
[2025-06-25T09:28:06.103+0200] {subprocess.py:93} INFO - [0m07:28:06  Concurrency: 1 threads (target='dev')
[2025-06-25T09:28:06.105+0200] {subprocess.py:93} INFO - [0m07:28:06
[2025-06-25T09:28:09.227+0200] {subprocess.py:93} INFO - [0m07:28:09  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T09:28:09.887+0200] {subprocess.py:93} INFO - [0m07:28:09  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.65s]
[2025-06-25T09:28:09.896+0200] {subprocess.py:93} INFO - [0m07:28:09  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T09:28:10.293+0200] {subprocess.py:93} INFO - [0m07:28:10  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.39s]
[2025-06-25T09:28:10.300+0200] {subprocess.py:93} INFO - [0m07:28:10  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T09:28:10.729+0200] {subprocess.py:93} INFO - [0m07:28:10  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.43s]
[2025-06-25T09:28:10.736+0200] {subprocess.py:93} INFO - [0m07:28:10  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T09:28:11.313+0200] {subprocess.py:93} INFO - [0m07:28:11  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.57s]
[2025-06-25T09:28:12.004+0200] {subprocess.py:93} INFO - [0m07:28:12
[2025-06-25T09:28:12.008+0200] {subprocess.py:93} INFO - [0m07:28:12  Finished running 4 view models in 0 hours 0 minutes and 5.90 seconds (5.90s).
[2025-06-25T09:28:12.116+0200] {subprocess.py:93} INFO - [0m07:28:12
[2025-06-25T09:28:12.118+0200] {subprocess.py:93} INFO - [0m07:28:12  [32mCompleted successfully[0m
[2025-06-25T09:28:12.120+0200] {subprocess.py:93} INFO - [0m07:28:12
[2025-06-25T09:28:12.122+0200] {subprocess.py:93} INFO - [0m07:28:12  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T09:28:12.590+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T09:28:12.669+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T072748, start_date=20250625T072757, end_date=20250625T072812
[2025-06-25T09:28:12.737+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T09:28:12.780+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
