[2025-06-25T11:48:37.060+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T08:00:00+00:00 [queued]>
[2025-06-25T11:48:37.079+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T08:00:00+00:00 [queued]>
[2025-06-25T11:48:37.080+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T11:48:37.142+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 08:00:00+00:00
[2025-06-25T11:48:37.319+0200] {standard_task_runner.py:57} INFO - Started process 231521 to run task
[2025-06-25T11:48:37.484+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T08:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp1yygk5vp']
[2025-06-25T11:48:37.495+0200] {standard_task_runner.py:85} INFO - Job 45: Subtask run_dbt_models
[2025-06-25T11:48:38.151+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T08:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T11:48:38.499+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T08:00:00+00:00'
[2025-06-25T11:48:38.512+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T11:48:38.726+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T11:48:39.291+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T11:48:53.589+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T11:48:53.590+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T11:48:55.855+0200] {subprocess.py:93} INFO - [0m09:48:55  Running with dbt=1.10.2
[2025-06-25T11:48:58.321+0200] {subprocess.py:93} INFO - [0m09:48:58  Registered adapter: snowflake=1.9.4
[2025-06-25T11:49:02.301+0200] {subprocess.py:93} INFO - [0m09:49:02  Found 4 models, 476 macros
[2025-06-25T11:49:02.306+0200] {subprocess.py:93} INFO - [0m09:49:02
[2025-06-25T11:49:02.308+0200] {subprocess.py:93} INFO - [0m09:49:02  Concurrency: 1 threads (target='dev')
[2025-06-25T11:49:02.309+0200] {subprocess.py:93} INFO - [0m09:49:02
[2025-06-25T11:49:07.092+0200] {subprocess.py:93} INFO - [0m09:49:07  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T11:49:08.204+0200] {subprocess.py:93} INFO - [0m09:49:08  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 1.10s]
[2025-06-25T11:49:08.212+0200] {subprocess.py:93} INFO - [0m09:49:08  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T11:49:08.591+0200] {subprocess.py:93} INFO - [0m09:49:08  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.38s]
[2025-06-25T11:49:08.603+0200] {subprocess.py:93} INFO - [0m09:49:08  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T11:49:09.160+0200] {subprocess.py:93} INFO - [0m09:49:09  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.55s]
[2025-06-25T11:49:09.166+0200] {subprocess.py:93} INFO - [0m09:49:09  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T11:49:09.688+0200] {subprocess.py:93} INFO - [0m09:49:09  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.52s]
[2025-06-25T11:49:10.397+0200] {subprocess.py:93} INFO - [0m09:49:10
[2025-06-25T11:49:10.401+0200] {subprocess.py:93} INFO - [0m09:49:10  Finished running 4 view models in 0 hours 0 minutes and 8.08 seconds (8.08s).
[2025-06-25T11:49:10.609+0200] {subprocess.py:93} INFO - [0m09:49:10
[2025-06-25T11:49:10.612+0200] {subprocess.py:93} INFO - [0m09:49:10  [32mCompleted successfully[0m
[2025-06-25T11:49:10.614+0200] {subprocess.py:93} INFO - [0m09:49:10
[2025-06-25T11:49:10.622+0200] {subprocess.py:93} INFO - [0m09:49:10  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T11:49:11.272+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T11:49:11.540+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T080000, start_date=20250625T094837, end_date=20250625T094911
[2025-06-25T11:49:11.589+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T11:49:11.635+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
