[2025-06-25T12:00:06.212+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T09:00:00+00:00 [queued]>
[2025-06-25T12:00:06.229+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T09:00:00+00:00 [queued]>
[2025-06-25T12:00:06.230+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T12:00:06.346+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 09:00:00+00:00
[2025-06-25T12:00:06.370+0200] {standard_task_runner.py:57} INFO - Started process 236576 to run task
[2025-06-25T12:00:06.406+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T09:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpdg1h5hxk']
[2025-06-25T12:00:06.435+0200] {standard_task_runner.py:85} INFO - Job 53: Subtask run_dbt_models
[2025-06-25T12:00:06.781+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T09:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T12:00:06.973+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T09:00:00+00:00'
[2025-06-25T12:00:06.977+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T12:00:06.979+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T12:00:07.139+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T12:00:09.740+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T12:00:09.741+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T12:00:10.594+0200] {subprocess.py:93} INFO - [0m10:00:10  Running with dbt=1.10.2
[2025-06-25T12:00:12.155+0200] {subprocess.py:93} INFO - [0m10:00:12  Registered adapter: snowflake=1.9.4
[2025-06-25T12:00:13.902+0200] {subprocess.py:93} INFO - [0m10:00:13  Found 4 models, 476 macros
[2025-06-25T12:00:13.910+0200] {subprocess.py:93} INFO - [0m10:00:13
[2025-06-25T12:00:13.917+0200] {subprocess.py:93} INFO - [0m10:00:13  Concurrency: 1 threads (target='dev')
[2025-06-25T12:00:13.919+0200] {subprocess.py:93} INFO - [0m10:00:13
[2025-06-25T12:00:16.930+0200] {subprocess.py:93} INFO - [0m10:00:16  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T12:00:17.536+0200] {subprocess.py:93} INFO - [0m10:00:17  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.60s]
[2025-06-25T12:00:17.541+0200] {subprocess.py:93} INFO - [0m10:00:17  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T12:00:17.877+0200] {subprocess.py:93} INFO - [0m10:00:17  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.33s]
[2025-06-25T12:00:17.884+0200] {subprocess.py:93} INFO - [0m10:00:17  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T12:00:18.241+0200] {subprocess.py:93} INFO - [0m10:00:18  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.35s]
[2025-06-25T12:00:18.249+0200] {subprocess.py:93} INFO - [0m10:00:18  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T12:00:18.745+0200] {subprocess.py:93} INFO - [0m10:00:18  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.49s]
[2025-06-25T12:00:19.467+0200] {subprocess.py:93} INFO - [0m10:00:19
[2025-06-25T12:00:19.469+0200] {subprocess.py:93} INFO - [0m10:00:19  Finished running 4 view models in 0 hours 0 minutes and 5.54 seconds (5.54s).
[2025-06-25T12:00:19.614+0200] {subprocess.py:93} INFO - [0m10:00:19
[2025-06-25T12:00:19.617+0200] {subprocess.py:93} INFO - [0m10:00:19  [32mCompleted successfully[0m
[2025-06-25T12:00:19.619+0200] {subprocess.py:93} INFO - [0m10:00:19
[2025-06-25T12:00:19.624+0200] {subprocess.py:93} INFO - [0m10:00:19  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T12:00:20.098+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T12:00:20.170+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T090000, start_date=20250625T100006, end_date=20250625T100020
[2025-06-25T12:00:20.214+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T12:00:20.252+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
