[2025-06-25T14:26:34.478+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T11:00:00+00:00 [queued]>
[2025-06-25T14:26:34.616+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T11:00:00+00:00 [queued]>
[2025-06-25T14:26:34.619+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T14:26:34.755+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 11:00:00+00:00
[2025-06-25T14:26:34.800+0200] {standard_task_runner.py:57} INFO - Started process 257188 to run task
[2025-06-25T14:26:35.082+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T11:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpnsksfeff']
[2025-06-25T14:26:35.136+0200] {standard_task_runner.py:85} INFO - Job 63: Subtask run_dbt_models
[2025-06-25T14:26:35.516+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T11:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T14:26:35.621+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T11:00:00+00:00'
[2025-06-25T14:26:35.625+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T14:26:35.627+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T14:26:35.661+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T14:26:40.690+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T14:26:40.691+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T14:26:47.812+0200] {subprocess.py:93} INFO - [0m12:26:47  Running with dbt=1.10.2
[2025-06-25T14:27:03.890+0200] {subprocess.py:93} INFO - [0m12:27:03  Registered adapter: snowflake=1.9.4
[2025-06-25T14:27:08.475+0200] {subprocess.py:93} INFO - [0m12:27:08  Found 4 models, 476 macros
[2025-06-25T14:27:08.519+0200] {subprocess.py:93} INFO - [0m12:27:08
[2025-06-25T14:27:08.521+0200] {subprocess.py:93} INFO - [0m12:27:08  Concurrency: 1 threads (target='dev')
[2025-06-25T14:27:08.523+0200] {subprocess.py:93} INFO - [0m12:27:08
[2025-06-25T14:27:17.102+0200] {subprocess.py:93} INFO - [0m12:27:17  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T14:27:18.185+0200] {subprocess.py:93} INFO - [0m12:27:18  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 1.08s]
[2025-06-25T14:27:18.190+0200] {subprocess.py:93} INFO - [0m12:27:18  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T14:27:18.639+0200] {subprocess.py:93} INFO - [0m12:27:18  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.45s]
[2025-06-25T14:27:18.644+0200] {subprocess.py:93} INFO - [0m12:27:18  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T14:27:19.114+0200] {subprocess.py:93} INFO - [0m12:27:19  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.47s]
[2025-06-25T14:27:19.122+0200] {subprocess.py:93} INFO - [0m12:27:19  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T14:27:19.919+0200] {subprocess.py:93} INFO - [0m12:27:19  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.78s]
[2025-06-25T14:27:20.648+0200] {subprocess.py:93} INFO - [0m12:27:20
[2025-06-25T14:27:20.655+0200] {subprocess.py:93} INFO - [0m12:27:20  Finished running 4 view models in 0 hours 0 minutes and 12.12 seconds (12.12s).
[2025-06-25T14:27:20.837+0200] {subprocess.py:93} INFO - [0m12:27:20
[2025-06-25T14:27:20.839+0200] {subprocess.py:93} INFO - [0m12:27:20  [32mCompleted successfully[0m
[2025-06-25T14:27:20.840+0200] {subprocess.py:93} INFO - [0m12:27:20
[2025-06-25T14:27:20.842+0200] {subprocess.py:93} INFO - [0m12:27:20  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T14:27:21.317+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T14:27:21.416+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T110000, start_date=20250625T122634, end_date=20250625T122721
[2025-06-25T14:27:21.484+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T14:27:21.535+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
