[2025-06-25T15:00:06.882+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T12:00:00+00:00 [queued]>
[2025-06-25T15:00:06.891+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T12:00:00+00:00 [queued]>
[2025-06-25T15:00:06.892+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T15:00:06.923+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 12:00:00+00:00
[2025-06-25T15:00:06.929+0200] {standard_task_runner.py:57} INFO - Started process 264222 to run task
[2025-06-25T15:00:06.962+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T12:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpr2doqt0j']
[2025-06-25T15:00:06.971+0200] {standard_task_runner.py:85} INFO - Job 67: Subtask run_dbt_models
[2025-06-25T15:00:07.076+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T12:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T15:00:07.182+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T12:00:00+00:00'
[2025-06-25T15:00:07.187+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T15:00:07.188+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T15:00:07.207+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T15:00:22.116+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T15:00:22.117+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T15:00:33.805+0200] {subprocess.py:93} INFO - [0m13:00:33  Running with dbt=1.10.2
[2025-06-25T15:00:53.663+0200] {subprocess.py:93} INFO - [0m13:00:53  Registered adapter: snowflake=1.9.4
[2025-06-25T15:01:03.643+0200] {subprocess.py:93} INFO - [0m13:01:03  Found 4 models, 476 macros
[2025-06-25T15:01:03.649+0200] {subprocess.py:93} INFO - [0m13:01:03
[2025-06-25T15:01:03.650+0200] {subprocess.py:93} INFO - [0m13:01:03  Concurrency: 1 threads (target='dev')
[2025-06-25T15:01:03.652+0200] {subprocess.py:93} INFO - [0m13:01:03
[2025-06-25T15:01:13.403+0200] {subprocess.py:93} INFO - [0m13:01:13  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T15:01:14.110+0200] {subprocess.py:93} INFO - [0m13:01:14  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.70s]
[2025-06-25T15:01:14.115+0200] {subprocess.py:93} INFO - [0m13:01:14  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T15:01:14.499+0200] {subprocess.py:93} INFO - [0m13:01:14  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.38s]
[2025-06-25T15:01:14.506+0200] {subprocess.py:93} INFO - [0m13:01:14  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T15:01:14.861+0200] {subprocess.py:93} INFO - [0m13:01:14  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.35s]
[2025-06-25T15:01:14.867+0200] {subprocess.py:93} INFO - [0m13:01:14  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T15:01:15.506+0200] {subprocess.py:93} INFO - [0m13:01:15  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.63s]
[2025-06-25T15:01:16.380+0200] {subprocess.py:93} INFO - [0m13:01:16
[2025-06-25T15:01:16.384+0200] {subprocess.py:93} INFO - [0m13:01:16  Finished running 4 view models in 0 hours 0 minutes and 12.72 seconds (12.72s).
[2025-06-25T15:01:16.463+0200] {subprocess.py:93} INFO - [0m13:01:16
[2025-06-25T15:01:16.464+0200] {subprocess.py:93} INFO - [0m13:01:16  [32mCompleted successfully[0m
[2025-06-25T15:01:16.466+0200] {subprocess.py:93} INFO - [0m13:01:16
[2025-06-25T15:01:16.467+0200] {subprocess.py:93} INFO - [0m13:01:16  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T15:01:17.125+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T15:01:17.305+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T120000, start_date=20250625T130006, end_date=20250625T130117
[2025-06-25T15:01:17.414+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T15:01:17.460+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
