[2025-06-25T09:18:11.824+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:17:36.691403+00:00 [queued]>
[2025-06-25T09:18:11.835+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:17:36.691403+00:00 [queued]>
[2025-06-25T09:18:11.835+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T09:18:11.878+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 07:17:36.691403+00:00
[2025-06-25T09:18:11.884+0200] {standard_task_runner.py:57} INFO - Started process 224529 to run task
[2025-06-25T09:18:11.921+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T07:17:36.691403+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp5w4j_ei0']
[2025-06-25T09:18:11.931+0200] {standard_task_runner.py:85} INFO - Job 35: Subtask run_dbt_models
[2025-06-25T09:18:12.046+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T07:17:36.691403+00:00 [running]> on host 192.168.152.131
[2025-06-25T09:18:12.255+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T07:17:36.691403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T07:17:36.691403+00:00'
[2025-06-25T09:18:12.263+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T09:18:12.265+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T09:18:12.408+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T09:18:16.989+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T09:18:16.991+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T09:18:18.561+0200] {subprocess.py:93} INFO - [0m07:18:18  Running with dbt=1.10.2
[2025-06-25T09:18:22.828+0200] {subprocess.py:93} INFO - [0m07:18:22  Registered adapter: snowflake=1.9.4
[2025-06-25T09:18:26.609+0200] {subprocess.py:93} INFO - [0m07:18:26  Found 4 models, 476 macros
[2025-06-25T09:18:26.617+0200] {subprocess.py:93} INFO - [0m07:18:26
[2025-06-25T09:18:26.620+0200] {subprocess.py:93} INFO - [0m07:18:26  Concurrency: 1 threads (target='dev')
[2025-06-25T09:18:26.624+0200] {subprocess.py:93} INFO - [0m07:18:26
[2025-06-25T09:18:30.873+0200] {subprocess.py:93} INFO - [0m07:18:30  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T09:18:31.473+0200] {subprocess.py:93} INFO - [0m07:18:31  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.59s]
[2025-06-25T09:18:31.480+0200] {subprocess.py:93} INFO - [0m07:18:31  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T09:18:31.821+0200] {subprocess.py:93} INFO - [0m07:18:31  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.34s]
[2025-06-25T09:18:31.829+0200] {subprocess.py:93} INFO - [0m07:18:31  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T09:18:32.201+0200] {subprocess.py:93} INFO - [0m07:18:32  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.37s]
[2025-06-25T09:18:32.209+0200] {subprocess.py:93} INFO - [0m07:18:32  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T09:18:32.727+0200] {subprocess.py:93} INFO - [0m07:18:32  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.52s]
[2025-06-25T09:18:33.408+0200] {subprocess.py:93} INFO - [0m07:18:33
[2025-06-25T09:18:33.410+0200] {subprocess.py:93} INFO - [0m07:18:33  Finished running 4 view models in 0 hours 0 minutes and 6.78 seconds (6.78s).
[2025-06-25T09:18:33.505+0200] {subprocess.py:93} INFO - [0m07:18:33
[2025-06-25T09:18:33.507+0200] {subprocess.py:93} INFO - [0m07:18:33  [32mCompleted successfully[0m
[2025-06-25T09:18:33.508+0200] {subprocess.py:93} INFO - [0m07:18:33
[2025-06-25T09:18:33.510+0200] {subprocess.py:93} INFO - [0m07:18:33  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T09:18:34.709+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T09:18:34.814+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T071736, start_date=20250625T071811, end_date=20250625T071834
[2025-06-25T09:18:34.870+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T09:18:34.916+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
