[2025-06-25T17:00:06.781+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T14:00:00+00:00 [queued]>
[2025-06-25T17:00:06.792+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T14:00:00+00:00 [queued]>
[2025-06-25T17:00:06.793+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T17:00:06.825+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 14:00:00+00:00
[2025-06-25T17:00:06.831+0200] {standard_task_runner.py:57} INFO - Started process 288578 to run task
[2025-06-25T17:00:06.862+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T14:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp3qx61ocj']
[2025-06-25T17:00:06.870+0200] {standard_task_runner.py:85} INFO - Job 71: Subtask run_dbt_models
[2025-06-25T17:00:06.992+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T14:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T17:00:07.168+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T14:00:00+00:00'
[2025-06-25T17:00:07.181+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T17:00:07.187+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T17:00:07.398+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T17:00:10.483+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T17:00:10.485+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T17:00:11.885+0200] {subprocess.py:93} INFO - [0m15:00:11  Running with dbt=1.10.2
[2025-06-25T17:00:13.320+0200] {subprocess.py:93} INFO - [0m15:00:13  Registered adapter: snowflake=1.9.4
[2025-06-25T17:00:14.924+0200] {subprocess.py:93} INFO - [0m15:00:14  Found 4 models, 476 macros
[2025-06-25T17:00:14.938+0200] {subprocess.py:93} INFO - [0m15:00:14
[2025-06-25T17:00:14.941+0200] {subprocess.py:93} INFO - [0m15:00:14  Concurrency: 1 threads (target='dev')
[2025-06-25T17:00:14.943+0200] {subprocess.py:93} INFO - [0m15:00:14
[2025-06-25T17:00:26.276+0200] {subprocess.py:93} INFO - [0m15:00:26  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T17:00:26.999+0200] {subprocess.py:93} INFO - [0m15:00:26  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.72s]
[2025-06-25T17:00:27.008+0200] {subprocess.py:93} INFO - [0m15:00:27  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T17:00:27.442+0200] {subprocess.py:93} INFO - [0m15:00:27  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.43s]
[2025-06-25T17:00:27.458+0200] {subprocess.py:93} INFO - [0m15:00:27  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T17:00:27.902+0200] {subprocess.py:93} INFO - [0m15:00:27  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.44s]
[2025-06-25T17:00:27.909+0200] {subprocess.py:93} INFO - [0m15:00:27  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T17:00:28.484+0200] {subprocess.py:93} INFO - [0m15:00:28  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.57s]
[2025-06-25T17:00:29.337+0200] {subprocess.py:93} INFO - [0m15:00:29
[2025-06-25T17:00:29.340+0200] {subprocess.py:93} INFO - [0m15:00:29  Finished running 4 view models in 0 hours 0 minutes and 14.39 seconds (14.39s).
[2025-06-25T17:00:29.415+0200] {subprocess.py:93} INFO - [0m15:00:29
[2025-06-25T17:00:29.417+0200] {subprocess.py:93} INFO - [0m15:00:29  [32mCompleted successfully[0m
[2025-06-25T17:00:29.418+0200] {subprocess.py:93} INFO - [0m15:00:29
[2025-06-25T17:00:29.420+0200] {subprocess.py:93} INFO - [0m15:00:29  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T17:00:30.037+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T17:00:30.111+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T140000, start_date=20250625T150006, end_date=20250625T150030
[2025-06-25T17:00:30.158+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T17:00:30.211+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
