[2025-06-25T11:49:17.883+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:45:17+00:00 [queued]>
[2025-06-25T11:49:17.891+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:45:17+00:00 [queued]>
[2025-06-25T11:49:17.892+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T11:49:17.925+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 09:45:17+00:00
[2025-06-25T11:49:17.931+0200] {standard_task_runner.py:57} INFO - Started process 232071 to run task
[2025-06-25T11:49:17.966+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'manual__2025-06-25T09:45:17+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpwyr3lg1y']
[2025-06-25T11:49:17.975+0200] {standard_task_runner.py:85} INFO - Job 46: Subtask run_dbt_models
[2025-06-25T11:49:18.085+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models manual__2025-06-25T09:45:17+00:00 [running]> on host 192.168.152.131
[2025-06-25T11:49:18.270+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T09:45:17+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T09:45:17+00:00'
[2025-06-25T11:49:18.280+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T11:49:18.315+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T11:49:18.404+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T11:49:22.214+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T11:49:22.215+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T11:49:23.127+0200] {subprocess.py:93} INFO - [0m09:49:23  Running with dbt=1.10.2
[2025-06-25T11:49:25.185+0200] {subprocess.py:93} INFO - [0m09:49:25  Registered adapter: snowflake=1.9.4
[2025-06-25T11:49:27.252+0200] {subprocess.py:93} INFO - [0m09:49:27  Found 4 models, 476 macros
[2025-06-25T11:49:27.258+0200] {subprocess.py:93} INFO - [0m09:49:27
[2025-06-25T11:49:27.318+0200] {subprocess.py:93} INFO - [0m09:49:27  Concurrency: 1 threads (target='dev')
[2025-06-25T11:49:27.319+0200] {subprocess.py:93} INFO - [0m09:49:27
[2025-06-25T11:49:29.773+0200] {subprocess.py:93} INFO - [0m09:49:29  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T11:49:30.379+0200] {subprocess.py:93} INFO - [0m09:49:30  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.59s]
[2025-06-25T11:49:30.389+0200] {subprocess.py:93} INFO - [0m09:49:30  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T11:49:30.800+0200] {subprocess.py:93} INFO - [0m09:49:30  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.41s]
[2025-06-25T11:49:30.811+0200] {subprocess.py:93} INFO - [0m09:49:30  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T11:49:31.176+0200] {subprocess.py:93} INFO - [0m09:49:31  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T11:49:31.187+0200] {subprocess.py:93} INFO - [0m09:49:31  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T11:49:31.802+0200] {subprocess.py:93} INFO - [0m09:49:31  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.61s]
[2025-06-25T11:49:32.509+0200] {subprocess.py:93} INFO - [0m09:49:32
[2025-06-25T11:49:32.511+0200] {subprocess.py:93} INFO - [0m09:49:32  Finished running 4 view models in 0 hours 0 minutes and 5.22 seconds (5.22s).
[2025-06-25T11:49:32.582+0200] {subprocess.py:93} INFO - [0m09:49:32
[2025-06-25T11:49:32.583+0200] {subprocess.py:93} INFO - [0m09:49:32  [32mCompleted successfully[0m
[2025-06-25T11:49:32.585+0200] {subprocess.py:93} INFO - [0m09:49:32
[2025-06-25T11:49:32.588+0200] {subprocess.py:93} INFO - [0m09:49:32  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T11:49:33.133+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T11:49:33.261+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T094517, start_date=20250625T094917, end_date=20250625T094933
[2025-06-25T11:49:33.428+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T11:49:33.493+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
