[2025-06-25T16:00:05.304+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T13:00:00+00:00 [queued]>
[2025-06-25T16:00:05.313+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T13:00:00+00:00 [queued]>
[2025-06-25T16:00:05.314+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T16:00:05.441+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 13:00:00+00:00
[2025-06-25T16:00:05.453+0200] {standard_task_runner.py:57} INFO - Started process 277530 to run task
[2025-06-25T16:00:05.480+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T13:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmps5fs4azv']
[2025-06-25T16:00:05.489+0200] {standard_task_runner.py:85} INFO - Job 69: Subtask run_dbt_models
[2025-06-25T16:00:05.595+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T13:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T16:00:05.695+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T13:00:00+00:00'
[2025-06-25T16:00:05.700+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T16:00:05.702+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T16:00:05.844+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T16:00:08.672+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T16:00:08.673+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T16:00:09.798+0200] {subprocess.py:93} INFO - [0m14:00:09  Running with dbt=1.10.2
[2025-06-25T16:00:11.040+0200] {subprocess.py:93} INFO - [0m14:00:11  Registered adapter: snowflake=1.9.4
[2025-06-25T16:00:12.560+0200] {subprocess.py:93} INFO - [0m14:00:12  Found 4 models, 476 macros
[2025-06-25T16:00:12.566+0200] {subprocess.py:93} INFO - [0m14:00:12
[2025-06-25T16:00:12.567+0200] {subprocess.py:93} INFO - [0m14:00:12  Concurrency: 1 threads (target='dev')
[2025-06-25T16:00:12.569+0200] {subprocess.py:93} INFO - [0m14:00:12
[2025-06-25T16:00:15.437+0200] {subprocess.py:93} INFO - [0m14:00:15  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T16:00:16.037+0200] {subprocess.py:93} INFO - [0m14:00:16  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.60s]
[2025-06-25T16:00:16.042+0200] {subprocess.py:93} INFO - [0m14:00:16  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T16:00:16.416+0200] {subprocess.py:93} INFO - [0m14:00:16  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.37s]
[2025-06-25T16:00:16.423+0200] {subprocess.py:93} INFO - [0m14:00:16  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T16:00:16.791+0200] {subprocess.py:93} INFO - [0m14:00:16  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T16:00:16.797+0200] {subprocess.py:93} INFO - [0m14:00:16  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T16:00:17.303+0200] {subprocess.py:93} INFO - [0m14:00:17  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.50s]
[2025-06-25T16:00:18.031+0200] {subprocess.py:93} INFO - [0m14:00:18
[2025-06-25T16:00:18.034+0200] {subprocess.py:93} INFO - [0m14:00:18  Finished running 4 view models in 0 hours 0 minutes and 5.46 seconds (5.46s).
[2025-06-25T16:00:18.135+0200] {subprocess.py:93} INFO - [0m14:00:18
[2025-06-25T16:00:18.137+0200] {subprocess.py:93} INFO - [0m14:00:18  [32mCompleted successfully[0m
[2025-06-25T16:00:18.139+0200] {subprocess.py:93} INFO - [0m14:00:18
[2025-06-25T16:00:18.141+0200] {subprocess.py:93} INFO - [0m14:00:18  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T16:00:18.715+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T16:00:18.787+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T130000, start_date=20250625T140005, end_date=20250625T140018
[2025-06-25T16:00:18.849+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T16:00:18.898+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
