[2025-06-25T13:00:06.523+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T10:00:00+00:00 [queued]>
[2025-06-25T13:00:06.532+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T10:00:00+00:00 [queued]>
[2025-06-25T13:00:06.533+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T13:00:06.564+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-25 10:00:00+00:00
[2025-06-25T13:00:06.570+0200] {standard_task_runner.py:57} INFO - Started process 251373 to run task
[2025-06-25T13:00:06.601+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'run_dbt_models', 'scheduled__2025-06-25T10:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmp5kbe9s80']
[2025-06-25T13:00:06.607+0200] {standard_task_runner.py:85} INFO - Job 59: Subtask run_dbt_models
[2025-06-25T13:00:06.705+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.run_dbt_models scheduled__2025-06-25T10:00:00+00:00 [running]> on host 192.168.152.131
[2025-06-25T13:00:06.827+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='atefatef648@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T10:00:00+00:00'
[2025-06-25T13:00:06.836+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T13:00:06.839+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source "/home/atef/dbt_env/bin/activate" && cd "/home/atef/project/E-Commerce-Order-Pipeline/dbt_ecommerce" && dbt run']
[2025-06-25T13:00:07.009+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T13:00:10.112+0200] {subprocess.py:93} INFO - /home/atef/dbt_env/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
[2025-06-25T13:00:10.112+0200] {subprocess.py:93} INFO -   backends.update(_get_backends("networkx.backends"))
[2025-06-25T13:00:11.361+0200] {subprocess.py:93} INFO - [0m11:00:11  Running with dbt=1.10.2
[2025-06-25T13:00:12.578+0200] {subprocess.py:93} INFO - [0m11:00:12  Registered adapter: snowflake=1.9.4
[2025-06-25T13:00:14.016+0200] {subprocess.py:93} INFO - [0m11:00:14  Found 4 models, 476 macros
[2025-06-25T13:00:14.021+0200] {subprocess.py:93} INFO - [0m11:00:14
[2025-06-25T13:00:14.023+0200] {subprocess.py:93} INFO - [0m11:00:14  Concurrency: 1 threads (target='dev')
[2025-06-25T13:00:14.025+0200] {subprocess.py:93} INFO - [0m11:00:14
[2025-06-25T13:00:17.334+0200] {subprocess.py:93} INFO - [0m11:00:17  1 of 4 START sql view model ANALYTICS.stg_customers ............................ [RUN]
[2025-06-25T13:00:18.012+0200] {subprocess.py:93} INFO - [0m11:00:18  1 of 4 OK created sql view model ANALYTICS.stg_customers ....................... [[32mSUCCESS 1[0m in 0.67s]
[2025-06-25T13:00:18.016+0200] {subprocess.py:93} INFO - [0m11:00:18  2 of 4 START sql view model ANALYTICS.stg_orders ............................... [RUN]
[2025-06-25T13:00:18.340+0200] {subprocess.py:93} INFO - [0m11:00:18  2 of 4 OK created sql view model ANALYTICS.stg_orders .......................... [[32mSUCCESS 1[0m in 0.32s]
[2025-06-25T13:00:18.345+0200] {subprocess.py:93} INFO - [0m11:00:18  3 of 4 START sql view model ANALYTICS.stg_shipments ............................ [RUN]
[2025-06-25T13:00:18.711+0200] {subprocess.py:93} INFO - [0m11:00:18  3 of 4 OK created sql view model ANALYTICS.stg_shipments ....................... [[32mSUCCESS 1[0m in 0.36s]
[2025-06-25T13:00:18.725+0200] {subprocess.py:93} INFO - [0m11:00:18  4 of 4 START sql view model ANALYTICS.order_status ............................. [RUN]
[2025-06-25T13:00:19.366+0200] {subprocess.py:93} INFO - [0m11:00:19  4 of 4 OK created sql view model ANALYTICS.order_status ........................ [[32mSUCCESS 1[0m in 0.63s]
[2025-06-25T13:00:20.134+0200] {subprocess.py:93} INFO - [0m11:00:20
[2025-06-25T13:00:20.136+0200] {subprocess.py:93} INFO - [0m11:00:20  Finished running 4 view models in 0 hours 0 minutes and 6.11 seconds (6.11s).
[2025-06-25T13:00:20.219+0200] {subprocess.py:93} INFO - [0m11:00:20
[2025-06-25T13:00:20.220+0200] {subprocess.py:93} INFO - [0m11:00:20  [32mCompleted successfully[0m
[2025-06-25T13:00:20.222+0200] {subprocess.py:93} INFO - [0m11:00:20
[2025-06-25T13:00:20.224+0200] {subprocess.py:93} INFO - [0m11:00:20  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-25T13:00:20.768+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T13:00:20.918+0200] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order_monitoring_dag16, task_id=run_dbt_models, execution_date=20250625T100000, start_date=20250625T110006, end_date=20250625T110020
[2025-06-25T13:00:21.003+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-25T13:00:21.082+0200] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
