[2025-06-25T08:56:50.236+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:56:05.309066+00:00 [queued]>
[2025-06-25T08:56:50.263+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:56:05.309066+00:00 [queued]>
[2025-06-25T08:56:50.267+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T08:56:50.358+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): check_delayed_orders> on 2025-06-25 06:56:05.309066+00:00
[2025-06-25T08:56:50.369+0200] {standard_task_runner.py:57} INFO - Started process 217050 to run task
[2025-06-25T08:56:50.421+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'check_delayed_orders', 'manual__2025-06-25T06:56:05.309066+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmphu3y13f5']
[2025-06-25T08:56:50.436+0200] {standard_task_runner.py:85} INFO - Job 29: Subtask check_delayed_orders
[2025-06-25T08:56:50.866+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:56:05.309066+00:00 [running]> on host 192.168.152.131
[2025-06-25T08:56:51.142+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='check_delayed_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T06:56:05.309066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T06:56:05.309066+00:00'
[2025-06-25T08:56:51.148+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T08:56:51.150+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/atef/project/E-Commerce-Order-Pipeline/airflow_project/dags/utils/check_delayed_orders.py"']
[2025-06-25T08:56:51.168+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T08:56:53.966+0200] {subprocess.py:93} INFO - ✅ Running Snowflake delayed orders check...
[2025-06-25T08:56:53.967+0200] {subprocess.py:93} INFO - ✅ Python path: /usr/bin/python
[2025-06-25T08:56:53.967+0200] {subprocess.py:93} INFO - ✅ Snowflake connector version: 3.15.0
[2025-06-25T08:56:53.968+0200] {subprocess.py:93} INFO - ✅ Connected to Snowflake
[2025-06-25T08:56:53.969+0200] {subprocess.py:93} INFO - ✅ Query Result: (1,)
[2025-06-25T08:56:53.974+0200] {subprocess.py:93} INFO - ❌ Error: 1 delayed orders found.
[2025-06-25T08:56:54.072+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-25T08:56:54.115+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-25T08:56:54.124+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=order_monitoring_dag16, task_id=check_delayed_orders, execution_date=20250625T065605, start_date=20250625T065650, end_date=20250625T065654
[2025-06-25T08:56:54.280+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task check_delayed_orders (Bash command failed. The command returned a non-zero exit code 1.; 217050)
[2025-06-25T08:56:54.311+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-25T08:56:54.364+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
