[2025-06-25T08:56:39.089+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:55:36.685105+00:00 [queued]>
[2025-06-25T08:56:39.098+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:55:36.685105+00:00 [queued]>
[2025-06-25T08:56:39.099+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-06-25T08:56:39.151+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): check_delayed_orders> on 2025-06-25 06:55:36.685105+00:00
[2025-06-25T08:56:39.158+0200] {standard_task_runner.py:57} INFO - Started process 216914 to run task
[2025-06-25T08:56:39.189+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag16', 'check_delayed_orders', 'manual__2025-06-25T06:55:36.685105+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/tmp/tmpcecnt5iq']
[2025-06-25T08:56:39.197+0200] {standard_task_runner.py:85} INFO - Job 28: Subtask check_delayed_orders
[2025-06-25T08:56:39.309+0200] {task_command.py:410} INFO - Running <TaskInstance: order_monitoring_dag16.check_delayed_orders manual__2025-06-25T06:55:36.685105+00:00 [running]> on host 192.168.152.131
[2025-06-25T08:56:39.457+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='imamzafar100@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag16' AIRFLOW_CTX_TASK_ID='check_delayed_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T06:55:36.685105+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T06:55:36.685105+00:00'
[2025-06-25T08:56:39.462+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-25T08:56:39.464+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/atef/project/E-Commerce-Order-Pipeline/airflow_project/dags/utils/check_delayed_orders.py"']
[2025-06-25T08:56:39.502+0200] {subprocess.py:86} INFO - Output:
[2025-06-25T08:56:43.206+0200] {subprocess.py:93} INFO - ✅ Running Snowflake delayed orders check...
[2025-06-25T08:56:43.206+0200] {subprocess.py:93} INFO - ✅ Python path: /usr/bin/python
[2025-06-25T08:56:43.207+0200] {subprocess.py:93} INFO - ✅ Snowflake connector version: 3.15.0
[2025-06-25T08:56:43.207+0200] {subprocess.py:93} INFO - ✅ Connected to Snowflake
[2025-06-25T08:56:43.207+0200] {subprocess.py:93} INFO - ✅ Query Result: (1,)
[2025-06-25T08:56:43.207+0200] {subprocess.py:93} INFO - ❌ Error: 1 delayed orders found.
[2025-06-25T08:56:43.292+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-25T08:56:43.332+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/atef/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-25T08:56:43.340+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=order_monitoring_dag16, task_id=check_delayed_orders, execution_date=20250625T065536, start_date=20250625T065639, end_date=20250625T065643
[2025-06-25T08:56:43.404+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task check_delayed_orders (Bash command failed. The command returned a non-zero exit code 1.; 216914)
[2025-06-25T08:56:43.439+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-25T08:56:43.550+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
